kube-controller-manager: {
  "Node \ncontroller".style.fill: white
  "Replication \ncontroller".style.fill: white
  "Endpoints \ncontroller".style.fill: white
  "Service \n account & \ntoken \ncontroller".style.fill: white
}

cloud-controller-manager: {
  "Node \n controller".style.fill: white
  "Route \n controller".style.fill: white
  "Service \n controller".style.fill: white
}
